# Generated by Django 4.1.7 on 2023-03-13 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomCours', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=100)),
                ('title', models.CharField(default='', max_length=70)),
                ('dateExamen', models.DateField(auto_now_add=True)),
                ('heureExamen', models.DurationField()),
                ('dureExamen', models.DurationField()),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens', to='salleExamen.cours')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='salleExamen.user')),
            ],
            bases=('salleExamen.user',),
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='salleExamen.user')),
                ('matiereEnseigne', models.CharField(max_length=20)),
            ],
            bases=('salleExamen.user',),
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='salleExamen.user')),
                ('anneeNaissance', models.CharField(max_length=20)),
            ],
            bases=('salleExamen.user',),
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomSalle', models.CharField(max_length=100)),
                ('capacite', models.IntegerField()),
                ('localisation', models.IntegerField()),
                ('disponibilite', models.BooleanField()),
                ('cours', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='salleExamen.cours')),
                ('examens', models.ManyToManyField(to='salleExamen.examen')),
            ],
        ),
        migrations.CreateModel(
            name='Planification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salleExamen.cours')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salleExamen.examen')),
            ],
        ),
        migrations.AddField(
            model_name='cours',
            name='enseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salleExamen.enseignant'),
        ),
    ]
