# Generated by Django 4.1.7 on 2023-03-15 18:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('salleExamen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planification',
            name='examen',
        ),
        migrations.RemoveField(
            model_name='salle',
            name='cours',
        ),
        migrations.RemoveField(
            model_name='salle',
            name='examens',
        ),
        migrations.AddField(
            model_name='cours',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cours',
            name='salle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='salleExamen.salle'),
        ),
        migrations.AddField(
            model_name='examen',
            name='salles',
            field=models.ManyToManyField(to='salleExamen.salle'),
        ),
        migrations.AddField(
            model_name='planification',
            name='datedebut',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planification',
            name='datefin',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salle',
            name='localisation',
            field=models.CharField(max_length=50),
        ),
    ]
