# Generated by Django 4.1.7 on 2023-03-19 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salleExamen', '0002_remove_planification_examen_remove_salle_cours_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cours',
            new_name='Matiere',
        ),
    ]
