# Generated by Django 4.1.7 on 2023-03-19 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salleExamen', '0003_rename_cours_matiere'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examen',
            old_name='cours',
            new_name='matiere',
        ),
        migrations.RenameField(
            model_name='matiere',
            old_name='nomCours',
            new_name='nom',
        ),
        migrations.RemoveField(
            model_name='matiere',
            name='salle',
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('duree', models.DurationField()),
                ('matiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='salleExamen.matiere')),
                ('salle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='salleExamen.salle')),
            ],
        ),
    ]
