# Generated by Django 4.1.7 on 2023-03-19 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salleExamen', '0004_rename_cours_examen_matiere_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enseignant',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='user_ptr',
        ),
        migrations.AlterField(
            model_name='matiere',
            name='enseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enseignant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Administration',
        ),
        migrations.DeleteModel(
            name='Enseignant',
        ),
        migrations.DeleteModel(
            name='Etudiant',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
